# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 874)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Toolbox = QtWidgets.QGroupBox(self.centralwidget)
        self.Toolbox.setGeometry(QtCore.QRect(10, 0, 1101, 101))
        self.Toolbox.setFlat(False)
        self.Toolbox.setCheckable(False)
        self.Toolbox.setChecked(False)
        self.Toolbox.setObjectName("Toolbox")
        self.toolButton = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton.setGeometry(QtCore.QRect(10, 20, 71, 68))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui icons/icons8-add-file-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("ui icons/folder_open.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("ui icons/document-icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(35, 35))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_2.setGeometry(QtCore.QRect(70, 20, 71, 68))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui icons/folder-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_3.setGeometry(QtCore.QRect(130, 20, 71, 68))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui icons/Files-Delete-File-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_4.setGeometry(QtCore.QRect(190, 20, 71, 68))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_5.setGeometry(QtCore.QRect(250, 20, 71, 68))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui icons/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_5.setIcon(icon4)
        self.toolButton_5.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.toolButton_6 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_6.setGeometry(QtCore.QRect(380, 20, 71, 68))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ui icons/zip-file-format-vector-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon5)
        self.toolButton_6.setIconSize(QtCore.QSize(37, 37))
        self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.toolButton_7 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_7.setGeometry(QtCore.QRect(530, 20, 71, 68))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ui icons/Go Back-595b40b75ba036ed117d8029.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_7.setIcon(icon6)
        self.toolButton_7.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_7.setAutoRaise(True)
        self.toolButton_7.setObjectName("toolButton_7")
        self.toolButton_8 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_8.setGeometry(QtCore.QRect(600, 20, 71, 68))
        self.toolButton_8.setInputMethodHints(QtCore.Qt.ImhNone)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ui icons/Circled Right-595b40b75ba036ed117d843c.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon7)
        self.toolButton_8.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_8.setAutoRaise(True)
        self.toolButton_8.setObjectName("toolButton_8")
        self.toolButton_9 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_9.setGeometry(QtCore.QRect(460, 20, 71, 68))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ui icons/fav.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setIcon(icon8)
        self.toolButton_9.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_9.setAutoRaise(True)
        self.toolButton_9.setObjectName("toolButton_9")
        self.toolButton_13 = QtWidgets.QToolButton(self.Toolbox)
        self.toolButton_13.setGeometry(QtCore.QRect(310, 20, 71, 68))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ui icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_13.setIcon(icon9)
        self.toolButton_13.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_13.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolButton_13.setAutoRaise(True)
        self.toolButton_13.setObjectName("toolButton_13")
        self.label = QtWidgets.QLabel(self.Toolbox)
        self.label.setGeometry(QtCore.QRect(1010, 20, 81, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("ui icons/152086959861286098.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setEnabled(True)
        self.treeWidget.setGeometry(QtCore.QRect(10, 110, 256, 691))
        self.treeWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.treeWidget.setTabKeyNavigation(False)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropOverwriteMode(True)
        self.treeWidget.setUniformRowHeights(False)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ui icons/my-computer-icon-81972.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.treeWidget.headerItem().setIcon(0, icon10)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("ui icons/Hdd-595b40b75ba036ed117d969e.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item_0.setIcon(0, icon11)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("ui icons/93096_235205_folder_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon12.addPixmap(QtGui.QPixmap("ui icons/folder_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item_1.setIcon(0, icon12)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setIcon(0, icon11)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("ui icons/folder_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon13.addPixmap(QtGui.QPixmap("ui icons/93096_235205_folder_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        item_1.setIcon(0, icon13)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(280, 150, 831, 551))
        self.tableWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableWidget.setStatusTip("")
        self.tableWidget.setAccessibleName("")
        self.tableWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setDragEnabled(False)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setIconSize(QtCore.QSize(25, 25))
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(1)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("ui icons/Folders-Add-Folder-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon14)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("ui icons/document-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon15)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(1, 2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(230)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(65)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(38)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 110, 791, 31))
        self.comboBox_2.setToolTipDuration(0)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_2.setIconSize(QtCore.QSize(22, 22))
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setModelColumn(0)
        self.comboBox_2.setObjectName("comboBox_2")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("ui icons/HDD-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox_2.addItem(icon16, "")
        self.toolButton_12 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_12.setGeometry(QtCore.QRect(1080, 110, 31, 31))
        self.toolButton_12.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("ui icons/a5d6aeadedbecb97856e1339f1cb2477.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_12.setIcon(icon17)
        self.toolButton_12.setIconSize(QtCore.QSize(35, 35))
        self.toolButton_12.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_12.setAutoRaise(True)
        self.toolButton_12.setObjectName("toolButton_12")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(280, 700, 831, 101))
        self.groupBox.setObjectName("groupBox")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 70, 811, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setMaximum(500)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setTracking(True)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.toolButton_11 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_11.setGeometry(QtCore.QRect(60, 20, 41, 41))
        self.toolButton_11.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("ui icons/pause-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_11.setIcon(icon18)
        self.toolButton_11.setIconSize(QtCore.QSize(42, 46))
        self.toolButton_11.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_11.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_11.setAutoRaise(True)
        self.toolButton_11.setObjectName("toolButton_11")
        self.toolButton_10 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_10.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.toolButton_10.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("ui icons/media.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_10.setIcon(icon19)
        self.toolButton_10.setIconSize(QtCore.QSize(42, 46))
        self.toolButton_10.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolButton_10.setAutoRaise(True)
        self.toolButton_10.setObjectName("toolButton_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1130, 10, 431, 791))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui icons/blank-file.png"))
        self.label_2.setObjectName("label_2")
        self.groupBox.raise_()
        self.Toolbox.raise_()
        self.treeWidget.raise_()
        self.tableWidget.raise_()
        self.comboBox_2.raise_()
        self.toolButton_12.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuView_2 = QtWidgets.QMenu(self.menubar)
        self.menuView_2.setObjectName("menuView_2")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_directiory = QtWidgets.QAction(MainWindow)
        self.actionOpen_directiory.setObjectName("actionOpen_directiory")
        self.menuFile.addAction(self.actionOpen_directiory)
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuView_2.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Toolbox.setTitle(_translate("MainWindow", "Toolbox"))
        self.toolButton.setText(_translate("MainWindow", "New "))
        self.toolButton_2.setText(_translate("MainWindow", "Open"))
        self.toolButton_3.setText(_translate("MainWindow", "Delete"))
        self.toolButton_4.setText(_translate("MainWindow", "Copy"))
        self.toolButton_5.setText(_translate("MainWindow", "Cut"))
        self.toolButton_6.setText(_translate("MainWindow", "Compress"))
        self.toolButton_7.setText(_translate("MainWindow", "Back"))
        self.toolButton_8.setText(_translate("MainWindow", "Forward"))
        self.toolButton_9.setText(_translate("MainWindow", "Favorites"))
        self.toolButton_13.setText(_translate("MainWindow", "Paste"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "My Computer "))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "C:/"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Mamad"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "mamaly"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "D:/"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "Reza"))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("MainWindow", "file1"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Data modified"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Filename"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "1399/1/23"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Pdf file"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.comboBox_2.setToolTip(_translate("MainWindow", "Enter Your Direction and press enter to save"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "C:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "C:"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "Edit"))
        self.menuView_2.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_directiory.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

